#
# Copyright 2016-2017 ForgeRock AS. All Rights Reserved
#
# Use of this code requires a commercial software license with ForgeRock AS.
# or with one of its affiliates. All use shall be exclusively subject
# to such license between the licensee and ForgeRock AS.
#
apiVersion: v1
kind: Service
metadata:
  name: postgres-openidm
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: dbport
  selector:
    app: openidm
    tier: repo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: openidm
    tier: repo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-openidm
  labels:
    app: openidm
    tier: repo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openidm
        tier: repo
    spec:
      containers:
      - image: forgerock/openidm-postgres:5.5.0
        name: postgres
        imagePullPolicy: IfNotPresent
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: password.txt
        - name: POSTGRES_USER
          value: openidm
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data/pgdata
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv-postgres
  persistentVolumeReclaimPolicy: Recycle
