#
# Copyright 2016-2017 ForgeRock AS. All Rights Reserved
#
# Use of this code requires a commercial software license with ForgeRock AS.
# or with one of its affiliates. All use shall be exclusively subject
# to such license between the licensee and ForgeRock AS.
#
apiVersion: v1
kind: Service
metadata:
  name: openidm 
  labels:
    app: getting-started
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30088
  selector:
    app: getting-started
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openidm
  labels:
    app: getting-started
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: getting-started
        tier: frontend
    spec:
      containers:
      - image: forgerock/openidm:5.5.0
        name: openidm
        args: ["-p","samples/devops-gettingstarted"]
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: postgres-openidm
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: password.txt
        ports:
        - containerPort: 8080
          name: openidm
        volumeMounts:
        - name: security
          mountPath: /opt/idmuser/openidm/security
      volumes:
      - name: security
        secret:
          secretName: secstores
          items:
          - key: keystore.jceks
            path: keystore.jceks
          - key: truststore
            path: truststore
